package tech.hiphone.commons.constants;

public interface ErrorCodeContants {
    String ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND";
    String INVALID_PASSWORD = "INVALID_PASSWORD";
    String LOGIN_ALREADY_USED = "LOGIN_ALREADY_USED";

    String UNAUTHORIZED = "UNAUTHORIZED";
    String LACK_OF_DATA = "LACK_OF_DATA";
    String BAD_PARAMETERS = "BAD_PARAMETERS";
    String THIRD_PRTY_ERROR = "THIRD_PRTY_ERROR";
    String REQUEST_FREQUENCE = "REQUEST_FREQUENCE";
    String NO_PRIVILEGE = "NO_PRIVILEGE"; // 没权限处理

    String ACCESS_DENIED = "ACCESS_DENIED";
    String VALIDATION_FAIL = "VALIDATION_FAIL";
    String METHOD_NOT_SUPPORTED = "METHOD_NOT_SUPPORTED";
    String CONCURRENCY_FAILURE = "CONCURRENCY_FAILURE";
    String OTHER_ERROR = "OTHER_ERROR";
    
    String USER_NOT_EXISTS = "USER_NOT_EXISTS";
    String USER_EXISTS = "USER_EXISTS";
    String DATA_FORMAT = "DATA_FORMAT";
    String ENCODE_FAIL = "ENCODE_FAIL";
    String DECODE_FAIL = "DECODE_FAIL";
    String DATA_EXISTS = "DATA_EXISTS";
    String NOT_SUPPORT = "NOT_SUPPORT";
    String NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

}
